name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: cryptoguy55
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the SVG to the output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
